from playwright.sync_api import sync_playwright, expect
def tam_kapsamli_e_ticaret_testi(playwright):
    browser = playwright.chromium.launch(headless=False, slow_mo=500)
    page = browser.new_page(viewport={"width": 1920, "height": 1080})
    print("1. Swag Labs e-ticaret sitesine giriş yapılıyor...")
    page.goto("https://www.saucedemo.com/")
    print("2. Kullanıcı bilgileri dolduruluyor ve sisteme giriliyor...")
    page.locator("#user-name").fill("standard_user")
    page.locator("#password").fill("secret_sauce")
    page.locator("#login-button").click()
    expect(page).to_have_url("https://www.saucedemo.com/inventory.html")
    print("3. Ürünler 'Pahalıdan Ucuza' (High to Low) doğru sıralanıyor...")
    page.locator(".product_sort_container").select_option(value="hilo")
    print("4. Listedeki en pahalı iki ürün sepete ekleniyor...")
    page.locator("#add-to-cart-sauce-labs-fleece-jacket").click()
    page.locator("#add-to-cart-sauce-labs-backpack").click()
    sepet_rozeti = page.locator(".shopping_cart_badge")
    expect(sepet_rozeti).to_have_text("2")
    print("5. Sepete gidiliyor ve ödeme (Checkout) adımı başlatılıyor...")
    page.locator(".shopping_cart_link").click()
    page.locator("#checkout").click()
    print("6. Müşteri adres ve kargo bilgileri dolduruluyor...")
    page.locator("#first-name").fill("Fatih")
    page.locator("#last-name").fill("Bilgisayar Programcılığı")
    page.locator("#postal-code").fill("35100") # Bornova posta kodu
    page.locator("#continue").click()
    print("7. Sipariş özeti onaylanıyor ve alışveriş bitiriliyor...")
    page.evaluate("window.scrollTo(0, document.body.scrollHeight)")
    page.locator("#finish").click()
    print("8. Siparişin başarıyla tamamlandığı doğrulanıyor...")
    onay_mesaji = page.locator(".complete-header")
    expect(onay_mesaji).to_have_text("Thank you for your order!")
    page.screenshot(path="final_projesi_basari_raporu.png")
    print("HARİKA! Tüm süreç hatasız tamamlandı. 'final_projesi_basari_raporu.png' kaydedildi.")
    page.wait_for_timeout(3000)
    browser.close()
if __name__ == "__main__":
    with sync_playwright() as playwright:
        tam_kapsamli_e_ticaret_testi(playwright)